version: "2"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "${VAR_DIR}/nginx/vhost.d/:/etc/nginx/vhost.d/:ro"
      - "${VAR_DIR}/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro"
    environment:
      DEFAULT_HOST: "${DEFAULT_HOST}"
    networks:
      - back-tier
      - front-tier
  mysql:
    image: mariadb
    restart: unless-stopped
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - "${VAR_DIR}/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - back-tier
  db-init:
    image: mariadb
    restart: "no"
    command: /db-init.sh
    links:
      - mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - "${VAR_DIR}/sites:/sites:ro"
      - "${ROOT_DIR}/containers/db-init/db-init.sh:/db-init.sh:ro"
    networks:
      - back-tier
