${SITE_NAME}:
  build:
    context: \${ROOT_DIR}/containers/wordpress
  image: \${PROJECT_NAME}_wordpress
  restart: unless-stopped
  hostname: ${SITE_NAME}
  links:
    - mysql
  external_links:
    - mailserver_mail_1:mail
  depends_on:
    - db-init
  volumes:
    - \${VAR_DIR}/sites/${SITE_NAME}/wp-content:/var/www/html/wp-content:ro
    - \${VAR_DIR}/sites/${SITE_NAME}/wp-content/uploads:/var/www/html/wp-content/uploads
    - \${VAR_DIR}/sites/${SITE_NAME}/robots.txt:/var/www/html/robots.txt:ro
    - \${ROOT_DIR}/containers/wordpress/apache-wordpress.conf:/etc/apache2/conf-enabled/xxx-wordpress.conf:ro
    - \${ROOT_DIR}/containers/wordpress/php.ini-\${ENV}:/usr/local/etc/php/php.ini:ro
    - \${ROOT_DIR}/containers/wordpress/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
  environment:
    WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    VIRTUAL_HOST: ${VIRTUAL_HOST}
  networks:
    - back-tier
    - mail-tier
